// <auto-generated />
using System;
using DecisionOS.Distribution.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DecisionOS.Distribution.Infrastructure.Migrations
{
    [DbContext(typeof(DecisionOsDbContext))]
    partial class DecisionOsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DecisionOS.Distribution.Domain.ActionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int?>("KpiDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KpiDefinitionId");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "PeriodEnd", "KpiDefinitionId");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KpiDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("ReasonSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KpiDefinitionId");

                    b.HasIndex("TenantId", "PeriodEnd")
                        .IsUnique();

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.BusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveKpiProfileCode")
                        .HasColumnType("text");

                    b.Property<string>("ChannelStructure")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationStructure")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThresholdProfileCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("VerticalLibraryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("VerticalLibraryId");

                    b.ToTable("BusinessProfiles");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Catalog.CatalogDriver", b =>
                {
                    b.Property<string>("DriverId")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceFields")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryModules")
                        .HasColumnType("text");

                    b.Property<string>("RelatedKpis")
                        .HasColumnType("text");

                    b.HasKey("DriverId");

                    b.ToTable("CatalogDrivers");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Catalog.CatalogDriverInfluencerMap", b =>
                {
                    b.Property<string>("DriverId")
                        .HasColumnType("text");

                    b.Property<string>("InfluencerId")
                        .HasColumnType("text");

                    b.Property<decimal?>("DefaultWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("text");

                    b.Property<string>("RuleNotes")
                        .HasColumnType("text");

                    b.HasKey("DriverId", "InfluencerId");

                    b.HasIndex("InfluencerId");

                    b.ToTable("CatalogDriverInfluencerMaps");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Catalog.CatalogInfluencer", b =>
                {
                    b.Property<string>("InfluencerId")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("DefaultSeverity")
                        .HasColumnType("text");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceFields")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryModules")
                        .HasColumnType("text");

                    b.Property<string>("RelatedKpis")
                        .HasColumnType("text");

                    b.HasKey("InfluencerId");

                    b.ToTable("CatalogInfluencers");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Catalog.CatalogKpi", b =>
                {
                    b.Property<string>("KpiId")
                        .HasColumnType("text");

                    b.Property<string>("Cadence")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("DefaultStatusModel")
                        .HasColumnType("text");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeveloperNotes")
                        .HasColumnType("text");

                    b.Property<string>("EntityScope")
                        .HasColumnType("text");

                    b.Property<string>("LegacyCode")
                        .HasColumnType("text");

                    b.Property<bool>("MgmtLayerCandidate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryDataNeeds")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryModules")
                        .HasColumnType("text");

                    b.HasKey("KpiId");

                    b.ToTable("CatalogKpis");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Catalog.CatalogKpiDriverMap", b =>
                {
                    b.Property<string>("KpiId")
                        .HasColumnType("text");

                    b.Property<string>("DriverId")
                        .HasColumnType("text");

                    b.Property<string>("MapType")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryModules")
                        .HasColumnType("text");

                    b.Property<string>("RuleNotes")
                        .HasColumnType("text");

                    b.HasKey("KpiId", "DriverId");

                    b.HasIndex("DriverId");

                    b.ToTable("CatalogKpiDriverMaps");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Catalog.CatalogModule", b =>
                {
                    b.Property<string>("ModuleCode")
                        .HasColumnType("text");

                    b.Property<string>("DefaultOutput")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryKpis")
                        .HasColumnType("text");

                    b.HasKey("ModuleCode");

                    b.ToTable("CatalogModules");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Catalog.CatalogOutputArea", b =>
                {
                    b.Property<string>("OutputAreaCode")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoutingNotes")
                        .HasColumnType("text");

                    b.HasKey("OutputAreaCode");

                    b.ToTable("CatalogOutputAreas");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Catalog.CatalogScoreComponent", b =>
                {
                    b.Property<string>("Component")
                        .HasColumnType("text");

                    b.Property<string>("ImplementationNotes")
                        .HasColumnType("text");

                    b.Property<string>("RequirementLevel")
                        .HasColumnType("text");

                    b.Property<string>("ValueRange")
                        .HasColumnType("text");

                    b.Property<decimal>("WeightPercent")
                        .HasColumnType("numeric");

                    b.HasKey("Component");

                    b.ToTable("CatalogScoreComponents");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.DriverDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BusinessProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PillarCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProfileId", "PillarCode", "DriverCode")
                        .IsUnique();

                    b.ToTable("DriverDefinitions");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.DriverValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedSummary")
                        .HasColumnType("text");

                    b.Property<string>("CatalogDriverId")
                        .HasColumnType("text");

                    b.Property<string>("Context")
                        .HasColumnType("text");

                    b.Property<decimal>("Current")
                        .HasColumnType("numeric");

                    b.Property<string>("CurrentSummary")
                        .HasColumnType("text");

                    b.Property<string>("Dimension1")
                        .HasColumnType("text");

                    b.Property<string>("Dimension2")
                        .HasColumnType("text");

                    b.Property<string>("DriverCode")
                        .HasColumnType("text");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FixProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("PillarCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetSummary")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WeekOverWeekDelta")
                        .HasColumnType("numeric");

                    b.Property<string>("WhyItMatters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodEnd", "PillarCode", "DriverName", "Rank");

                    b.ToTable("DriverValues");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.ImportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverRowsProcessed")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("KpiRowsProcessed")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("ReadinessStatus")
                        .HasColumnType("text");

                    b.Property<string>("SourceFingerprint")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationSummary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodEnd", "SourceFingerprint");

                    b.HasIndex("TenantId", "PeriodEnd", "StartedAt");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.ImportRunIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Field")
                        .HasColumnType("text");

                    b.Property<int>("ImportRunId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "Severity");

                    b.ToTable("ImportRunIssues");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.InfluencerDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BusinessProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InfluencerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PillarCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProfileId", "PillarCode", "DriverCode", "InfluencerCode")
                        .IsUnique();

                    b.ToTable("InfluencerDefinitions");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.KpiDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertPriority")
                        .HasColumnType("integer");

                    b.Property<decimal>("AmberThreshold")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("BusinessProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiagnosticChecks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RedThreshold")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Target")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProfileId", "Code")
                        .IsUnique();

                    b.ToTable("KpiDefinitions");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.KpiSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardDetailLine1")
                        .HasColumnType("text");

                    b.Property<string>("CardDetailLine2")
                        .HasColumnType("text");

                    b.Property<string>("DataConfidence")
                        .HasColumnType("text");

                    b.Property<int>("KpiDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WeekOverWeekDelta")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("KpiDefinitionId");

                    b.HasIndex("TenantId", "PeriodEnd", "KpiDefinitionId")
                        .IsUnique();

                    b.ToTable("KpiSnapshots");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Normalized.NormalizedApRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgingBucket")
                        .HasColumnType("text");

                    b.Property<string>("BillId")
                        .HasColumnType("text");

                    b.Property<int?>("DaysPastDue")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("IssueSummary")
                        .HasColumnType("text");

                    b.Property<decimal?>("OpenBalance")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("UploadBatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("UploadedFileId")
                        .HasColumnType("bigint");

                    b.Property<string>("VendorId")
                        .HasColumnType("text");

                    b.Property<string>("VendorName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodEnd");

                    b.HasIndex("UploadBatchId", "UploadedFileId");

                    b.ToTable("NormalizedApRows");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Normalized.NormalizedArRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgingBucket")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<int?>("DaysPastDue")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("text");

                    b.Property<string>("IssueSummary")
                        .HasColumnType("text");

                    b.Property<decimal?>("OpenBalance")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("UploadBatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("UploadedFileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodEnd");

                    b.HasIndex("UploadBatchId", "UploadedFileId");

                    b.ToTable("NormalizedArRows");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Normalized.NormalizedInventoryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AverageCost")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InventoryValue")
                        .HasColumnType("numeric");

                    b.Property<string>("IssueSummary")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("LastSaleDate")
                        .HasColumnType("date");

                    b.Property<string>("LocationId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<decimal?>("QuantityOnHand")
                        .HasColumnType("numeric");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkuId")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("UploadBatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("UploadedFileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodEnd");

                    b.HasIndex("UploadBatchId", "UploadedFileId");

                    b.ToTable("NormalizedInventoryRows");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Normalized.NormalizedSalesRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Cogs")
                        .HasColumnType("numeric");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<decimal?>("GrossProfit")
                        .HasColumnType("numeric");

                    b.Property<string>("IssueSummary")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .HasColumnType("text");

                    b.Property<decimal?>("NetSales")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text");

                    b.Property<decimal?>("QuantitySold")
                        .HasColumnType("numeric");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkuId")
                        .HasColumnType("text");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<long>("UploadBatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("UploadedFileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodEnd");

                    b.HasIndex("UploadBatchId", "UploadedFileId");

                    b.ToTable("NormalizedSalesRows");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Routing.RoutingQueueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CatalogDriverId")
                        .HasColumnType("text");

                    b.Property<string>("CatalogKpiId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("numeric");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("text");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodEnd", "QueueType");

                    b.ToTable("RoutingQueueItems");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Scoring.InfluencerEvidence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Confidence")
                        .HasColumnType("text");

                    b.Property<int>("DriverValueId")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenceSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InfluencerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("Severity")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverValueId");

                    b.HasIndex("InfluencerId");

                    b.HasIndex("TenantId", "PeriodEnd", "DriverValueId");

                    b.ToTable("InfluencerEvidences");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Scoring.IssuePriorityScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ActionabilityScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CashScore")
                        .HasColumnType("numeric");

                    b.Property<string>("CatalogKpiId")
                        .HasColumnType("text");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FinancialScore")
                        .HasColumnType("numeric");

                    b.Property<int?>("KpiDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<decimal>("SeverityScore")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UrgencyScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CatalogKpiId");

                    b.HasIndex("KpiDefinitionId");

                    b.HasIndex("TenantId", "PeriodEnd", "CatalogKpiId");

                    b.HasIndex("TenantId", "PeriodEnd", "KpiDefinitionId")
                        .IsUnique();

                    b.ToTable("IssuePriorityScores");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Scoring.TenantKpiSelection", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogKpiId")
                        .HasColumnType("text");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.HasKey("TenantId", "CatalogKpiId");

                    b.HasIndex("CatalogKpiId");

                    b.ToTable("TenantKpiSelections");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Archetype")
                        .HasColumnType("text");

                    b.Property<Guid?>("BusinessProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProfileId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.TenantDriverOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DriverCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PillarCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PillarCode", "DriverCode")
                        .IsUnique();

                    b.ToTable("TenantDriverOverrides");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.TenantKpiOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertPriority")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AmberThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("DiagnosticChecks")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KpiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("text");

                    b.Property<decimal?>("RedThreshold")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Target")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "KpiCode")
                        .IsUnique();

                    b.ToTable("TenantKpiOverrides");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.MappingRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ignore")
                        .HasColumnType("boolean");

                    b.Property<long>("MappingTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceColumn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemField")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MappingTemplateId", "SourceColumn")
                        .IsUnique();

                    b.ToTable("MappingRules");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.MappingTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReportType", "Name")
                        .IsUnique();

                    b.ToTable("MappingTemplates");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.UploadBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("AnchorPeriodEnd")
                        .HasColumnType("date");

                    b.Property<int?>("Cadence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectionSummaryJson")
                        .HasColumnType("text");

                    b.Property<int>("ImportMode")
                        .HasColumnType("integer");

                    b.Property<int?>("ImportRunId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("ReadinessStatus")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationSummary")
                        .HasColumnType("text");

                    b.Property<string>("WorkbookFingerprint")
                        .HasColumnType("text");

                    b.Property<string>("WorkbookStoredRelativePath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId");

                    b.HasIndex("TenantId", "PeriodEnd");

                    b.ToTable("UploadBatches");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.UploadBatchIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Field")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<long>("UploadBatchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UploadedFileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UploadedFileId");

                    b.HasIndex("UploadBatchId", "Severity");

                    b.ToTable("UploadBatchIssues");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.UploadedFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("HeaderRowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("ReportType")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256Hex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredRelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UploadBatchId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sha256Hex");

                    b.HasIndex("UploadBatchId", "ReportType");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.UploadedFileColumnMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ignore")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceColumn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemField")
                        .HasColumnType("text");

                    b.Property<long>("UploadedFileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UploadedFileId", "SourceColumn")
                        .IsUnique();

                    b.ToTable("UploadedFileColumnMaps");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.VerticalLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("VerticalLibraries");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.WeeklyFocus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DecisionQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KpiDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("WhyNow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KpiDefinitionId");

                    b.HasIndex("TenantId", "PeriodEnd")
                        .IsUnique();

                    b.ToTable("WeeklyFocuses");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Workflow.HoldoverComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverValueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverValueId");

                    b.ToTable("HoldoverComments");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Workflow.HoldoverStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DriverValueId")
                        .HasColumnType("integer");

                    b.Property<int?>("FixProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DriverValueId");

                    b.ToTable("HoldoverStatusHistories");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Workflow.UserNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Workflow.WorkAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssigneeUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodEnd", "TargetType", "TargetId");

                    b.ToTable("WorkAssignments");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Infrastructure.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.ActionItem", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.KpiDefinition", "KpiDefinition")
                        .WithMany()
                        .HasForeignKey("KpiDefinitionId");

                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KpiDefinition");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Alert", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.KpiDefinition", "KpiDefinition")
                        .WithMany()
                        .HasForeignKey("KpiDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KpiDefinition");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.BusinessProfile", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.VerticalLibrary", "VerticalLibrary")
                        .WithMany()
                        .HasForeignKey("VerticalLibraryId");

                    b.Navigation("VerticalLibrary");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Catalog.CatalogDriverInfluencerMap", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Catalog.CatalogDriver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionOS.Distribution.Domain.Catalog.CatalogInfluencer", "Influencer")
                        .WithMany()
                        .HasForeignKey("InfluencerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Influencer");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Catalog.CatalogKpiDriverMap", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Catalog.CatalogDriver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionOS.Distribution.Domain.Catalog.CatalogKpi", "Kpi")
                        .WithMany()
                        .HasForeignKey("KpiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Kpi");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.DriverDefinition", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.BusinessProfile", "BusinessProfile")
                        .WithMany()
                        .HasForeignKey("BusinessProfileId");

                    b.Navigation("BusinessProfile");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.DriverValue", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.ImportRun", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.ImportRunIssue", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.ImportRun", "ImportRun")
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.InfluencerDefinition", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.BusinessProfile", "BusinessProfile")
                        .WithMany()
                        .HasForeignKey("BusinessProfileId");

                    b.Navigation("BusinessProfile");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.KpiDefinition", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.BusinessProfile", "BusinessProfile")
                        .WithMany()
                        .HasForeignKey("BusinessProfileId");

                    b.Navigation("BusinessProfile");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.KpiSnapshot", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.KpiDefinition", "KpiDefinition")
                        .WithMany()
                        .HasForeignKey("KpiDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KpiDefinition");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Routing.RoutingQueueItem", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Scoring.InfluencerEvidence", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.DriverValue", "DriverValue")
                        .WithMany()
                        .HasForeignKey("DriverValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionOS.Distribution.Domain.Catalog.CatalogInfluencer", "Influencer")
                        .WithMany()
                        .HasForeignKey("InfluencerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverValue");

                    b.Navigation("Influencer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Scoring.IssuePriorityScore", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Catalog.CatalogKpi", "CatalogKpi")
                        .WithMany()
                        .HasForeignKey("CatalogKpiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DecisionOS.Distribution.Domain.KpiDefinition", "KpiDefinition")
                        .WithMany()
                        .HasForeignKey("KpiDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogKpi");

                    b.Navigation("KpiDefinition");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Scoring.TenantKpiSelection", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Catalog.CatalogKpi", "CatalogKpi")
                        .WithMany()
                        .HasForeignKey("CatalogKpiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogKpi");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Tenant", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.BusinessProfile", "BusinessProfile")
                        .WithMany()
                        .HasForeignKey("BusinessProfileId");

                    b.Navigation("BusinessProfile");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.TenantDriverOverride", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.TenantKpiOverride", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.MappingRule", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Uploads.MappingTemplate", "MappingTemplate")
                        .WithMany("Rules")
                        .HasForeignKey("MappingTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MappingTemplate");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.MappingTemplate", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.UploadBatch", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.ImportRun", "ImportRun")
                        .WithMany()
                        .HasForeignKey("ImportRunId");

                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportRun");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.UploadBatchIssue", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Uploads.UploadBatch", "UploadBatch")
                        .WithMany()
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionOS.Distribution.Domain.Uploads.UploadedFile", "UploadedFile")
                        .WithMany()
                        .HasForeignKey("UploadedFileId");

                    b.Navigation("UploadBatch");

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.UploadedFile", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Uploads.UploadBatch", "UploadBatch")
                        .WithMany("Files")
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadBatch");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.UploadedFileColumnMap", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Uploads.UploadedFile", "UploadedFile")
                        .WithMany()
                        .HasForeignKey("UploadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.WeeklyFocus", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.KpiDefinition", "KpiDefinition")
                        .WithMany()
                        .HasForeignKey("KpiDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KpiDefinition");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Workflow.HoldoverComment", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.DriverValue", "DriverValue")
                        .WithMany()
                        .HasForeignKey("DriverValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverValue");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Workflow.HoldoverStatusHistory", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.DriverValue", "DriverValue")
                        .WithMany()
                        .HasForeignKey("DriverValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverValue");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Workflow.WorkAssignment", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionOS.Distribution.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DecisionOS.Distribution.Infrastructure.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.MappingTemplate", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("DecisionOS.Distribution.Domain.Uploads.UploadBatch", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
